<?php

namespace Devschool\BiblioBundle\Repository;

/**
 * cinemaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cinemaRepository extends \Doctrine\ORM\EntityRepository
{
}
